version: '3'

services:
    mysql:
        container_name: "${PROJECT_NAME}_mysql"
        build:
            context: ./docker/mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "${DATABASE_PORT}:3306"
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql/data/:/var/lib/mysql

    php:
        container_name: "${PROJECT_NAME}_php"
        build:
            context: ./docker/php
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:3306/${DATABASE_NAME}?serverVersion=5.7
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql

    nginx:
        container_name: "${PROJECT_NAME}_nginx"
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - "${PROJECT_BASE_PORT}:80"
            - "443:443"
        depends_on:
            - php

    pma:
        container_name: "${PROJECT_NAME}_pma"
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: $DATABASE_HOST
            PMA_USER: $DATABASE_USER
            PMA_PASSWORD: $DATABASE_PASSWORD
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        ports:
            - "8081:80"
        depends_on:
            - nginx
